export const productDatas = [
  {
    id: "1",
    title: "Classic Winter Jacket",
    status: "New Arrival",
    season: "Winter",
    images: [
      "https://img.freepik.com/premium-photo/young-hipster-man-with-laptop-hand-with-urban-look-city_75916-930.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/young-woman-wearing-jacket-walking-outside_1303-25124.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/beautiful-girl-fashionable-hat-gloves-walking-down-street_160672-26866.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/young-attractive-male-posing-nature_181624-46384.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 120,
    description: "A warm and stylish jacket perfect for winter outings.",
    reviews: 4.5,
    stock: 15,
    likes: 120,
    comments: 25,
    category: "Outerwear",
    quantity: 31,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "Brown", "purple", "Green"],
    gender: "Men",
  },
  {
    id: "2",
    title: "Elegant Evening Gown",
    status: "New Arrival",
    season: "Winter",
    images: [
      "https://img.freepik.com/free-photo/beautiful-bride-white-wedding-dress_144627-41225.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/girl-beautiful-black-dress-stands-near-window-looks-out-window_156140-2622.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/young-sexy-blond-woman-model-evening-dress-posing-blue-sky-background_158538-9190.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/front-view-elegant-girl-red-dress-leans-chair-looks-camera_8353-11655.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 220,
    description: "A stunning evening gown designed to make you shine.",
    reviews: 4.8,
    stock: 10,
    likes: 140,
    comments: 30,
    category: "Dresses",
    quantity: 11,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Black", "Green", "Red"],
    gender: "Women",
  },
  {
    id: "3",
    title: "Stylish Kids Winter Coat",
    status: "New Arrival",
    season: "Winter",
    images: [
      "https://img.freepik.com/premium-photo/adorable-happy-little-girl-outdoors-european-city_109800-2249.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/young-woman-talking-phone_329181-14871.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/child-model-smile-with-long-blond-hair-girl-black-coat-pink-scarf-orange-background-kid-beauty-look-hairstyle-autumn-fashion-style-trend-happy-childhood-concept_474717-12067.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 80,
    description: "Keep your kids warm and stylish this winter.",
    reviews: 4.6,
    stock: 20,
    likes: 95,
    comments: 15,
    category: "Outerwear",
    quantity: 91,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["SkyBlue", "Brown", "Black"],
    gender: "Kid",
  },
  {
    id: "4",
    title: "Summer Linen Shirt",
    status: "New Arrival",
    season: "Summer",
    images: [
      "https://img.freepik.com/free-photo/young-man-streets-provincial-spanish-city_72229-592.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/bottom-view-portrait-stylish-man_23-2148194058.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/portrait-handsome-bearded-man-shirt-beach_231834-3824.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 55,
    description: "Lightweight and breathable linen shirt for hot summer days.",
    reviews: 4.3,
    stock: 25,
    likes: 80,
    comments: 10,
    category: "Shirts",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Green", "Skyblue"],
    gender: "Men",
  },

  {
    id: "5",
    title: "Chic Summer Dress",
    status: "New Arrival",
    season: "Summer",
    images: [
      "https://img.freepik.com/free-photo/attractive-young-woman-blue-dress-straw-hat-walking-tropical-spa-villa-hotel-vacation-summer-style-outfit-sexy_285396-2476.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/happy-cute-romantic-caucasian-woman-summer-elegant-white-open-back-dress-straw-hat_343596-323.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/stylish-woman-red-hat-blue-wall-printed-outfit-summer-style-fashion-trend-top-skirt-skinny-straw-handbag-sunglasses-accessories-smiling-tropical-vacation-footwear-sandals-wedge_285396-4252.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",

      "https://img.freepik.com/free-photo/magnificent-positive-young-stylish-blogger-woman-posing-street-wearing-feminine-trendy-dress-straw-bag-soft-sunny-colors-summer-vacation-time_291049-2563.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],

    price: 100,
    description: "A chic dress perfect for sunny summer days.",
    reviews: 4.7,
    stock: 12,
    likes: 110,
    comments: 20,
    category: "Dresses",
    quantity: 41,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "White", "Red", "Skyblue"],
    gender: "Women",
  },
  {
    id: "6",
    title: "Kids Summer T-Shirt",
    status: "New Arrival",
    season: "Summer",
    images: [
      "https://img.freepik.com/premium-photo/young-girl-summer-studio_401765-1265.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/adorable-boy-playing-beach-white-back-ground_58409-1043.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/close-up-boy-smiling-while-holding-hat_1048944-17833889.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 30,
    description: "Soft and colorful t-shirt for kids to enjoy summer fun.",
    reviews: 4.9,
    stock: 30,
    likes: 70,
    comments: 5,
    category: "T-Shirts",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Green", "Blue"],
    gender: "Kid",
  },
  {
    id: "7",
    title: "Formal Men’s Suit",
    status: "Top Sell",
    season: "Winter",
    images: [
      "https://img.freepik.com/free-photo/bouquet-beautiful-peonies-road_144627-4191.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/only-allow-effective-people-business-casual-style-giving-man-confidence-senior-employee-brutal-bearded-man-blue-formalwear-businessman-has-long-beard-hair-salon-barbershop_474717-21567.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/portrait-happy-smiling-young-businessman-brown-suit-isolated-white-wall_231208-9214.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 300,
    description: "A premium suit for business and formal occasions.",
    reviews: 4.9,
    stock: 5,
    likes: 200,
    comments: 45,
    category: "Suits",
    quantity: 31,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "Blue", "maroon"],
    gender: "Men",
  },

  {
    id: "8",
    title: "Women's Office Blazer",
    status: "Top Sell",
    season: "Winter",
    images: [
      "https://img.freepik.com/premium-photo/beautiful-young-girl-autumn-park_104263-99.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/portrait-young-business-lady_1163-3180.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/smiling-woman-with-brown-jacket_1098-1290.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/stylish-businesswoman-with-clipboard-city_23-2147989588.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 180,
    description: "A classic blazer for professional settings.",
    reviews: 4.6,
    stock: 8,
    likes: 170,
    comments: 35,
    category: "Outerwear",
    quantity: 31,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "White", "maroon", "Gary"],
    gender: "Women",
  },
  {
    id: "9",
    title: "Casual Sneakers",
    status: "Upcoming",
    season: "Summer",
    images: [
      "https://img.freepik.com/premium-photo/woman-holding-bouquet-flowers-with-her-bicycle-outdoors_23-2148765652.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/girl-with-orange-shoes_144627-12935.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/man-jeans-with-cardboard-bouquet-flowers_114579-2389.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 75,
    description: "Comfortable and stylish sneakers for everyday wear.",
    reviews: 4.5,
    stock: 50,
    likes: 55,
    comments: 6,
    category: "Footwear",
    quantity: 41,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Orange", "Blue"],
    gender: "Men",
  },
  {
    id: "10",
    title: "Stylish Kid’s Backpack",
    status: "Upcoming",
    season: "Summer",
    images: [
      "https://img.freepik.com/premium-photo/modern-lifestyle-student-life-listen-music-headphones-teen-girl-open-backpack-lifestyle-education-back-school-school-education-adolescence-lifestyle-teen-girl-school-student-outdoor_474717-176764.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/sports-training-cute-primary-school-girl-white-tshirt-skirt-standing-big-sports-blue-bag-her-shoulder_465992-390.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/school-boy-holding-bag-smiling_130153-500.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/cute-girl-with-schoolbag_144627-26605.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 50,
    description: "Perfect for school or travel, designed for kids.",
    reviews: 4.9,
    stock: 20,
    likes: 44,
    comments: 8,
    category: "Accessories",
    quantity: 11,
    sizes: [],
    colors: ["Lime", "Blue", "Yellow", "Pink"],
    gender: "Kid",
  },

  {
    id: "11",
    title: "Trendy Men’s Polo Shirt",
    status: "Upcoming",
    season: "Summer",
    images: [
      "https://img.freepik.com/premium-photo/handsome-man-wearing-styled-sunglasses-marsala-clothes_136403-6716.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/portrait-young-man-standing-against-wall_1048944-23872785.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/distracted-caucasian-man-with-modern-clothes-tattoos-piercing-leaning-rail-park_475667-764.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 40,
    description: "A classic polo shirt for casual outings.",
    reviews: 4.5,
    stock: 35,
    likes: 7,
    comments: 33,
    category: "Shirts",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Red", "SandyBrown", "Black"],
    gender: "Men",
  },
  {
    id: "12",
    title: "Elegant Women's Handbag",
    status: "Upcoming",
    season: "Summer",
    images: [
      "https://img.freepik.com/free-photo/red-haired-girl-with-red-handbag-posed-near-vintage-house_627829-10025.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/boots_1303-4425.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/woman-striped-blazer-trousers-holding-small-blue-bag_140725-2687.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/female-hands-close-up-holding-bag-flowers_1303-27882.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 150,
    description: "A stylish handbag to complement your outfit.",
    reviews: 4.7,
    stock: 18,
    likes: 6,
    comments: 33,
    category: "Accessories",
    quantity: 13,
    sizes: ["LG", "SM"],
    colors: ["Red", "Black", "SkyBlue", "NavajoWhite"],
    gender: "Women",
  },
  {
    id: "13",
    title: "Warm Knitted Scarf",
    status: "Top Sell",
    season: "Winter",
    images: [
      "https://img.freepik.com/premium-photo/winter-fashion-knitted-clothes-man-knitted-hat-gloves-scarf-winter-fashion-man-wear-knitted-accessory-turquoise-background-winter-accessories-concept-knitted-accessories-as-hat-scarf_474717-154265.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/picture-handsome-man-warm-sweater-hat-scarf_380164-25287.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/knitted-accessories-as-hat-scarf-man-knitted-hat-scarf-winter-fashion-season-man-wear-knitted-clothes-turquoise-background-winter-accessories-concept-winter-fashion-knitted-clothes_474717-15447.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 25,
    description: "A cozy scarf to keep you warm and stylish.",
    reviews: 4.7,
    stock: 40,
    likes: 110,
    comments: 20,
    category: "Accessories",
    quantity: 1,
    sizes: ["LG", "MD", "SM"],
    colors: ["Goldenrod", "White", "OliveDrab"],
    gender: "Men",
  },
  {
    id: "14",
    title: "Kids Winter Boots",
    status: "Top Sell",
    season: "Winter",
    images: [
      "https://img.freepik.com/premium-photo/autumn-time-little-kid-fall_109800-15147.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/girl-playing-with-sword_23-2147782167.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/portrait-young-girl-with-ice-skates-outdoors-winter_23-2149328459.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 60,
    description: "Durable boots for kids to enjoy snowy adventures.",
    reviews: 4.8,
    stock: 20,
    likes: 140,
    comments: 18,
    category: "Footwear",
    quantity: 16,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["IndianRed", "Black", "White"],
    gender: "Kid",
  },
  {
    id: "15",
    title: "Leather Men's Belt",
    status: "Regular",
    season: "Winter",
    images: [
      "https://img.freepik.com/free-photo/morning-groom_1303-11598.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/fashion-portrait-young-businessman-handsome-model-man-dressed-elegant-brown-suit-with-accessories_158538-11193.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/mens-blue-leather-belt-trousers-blue-belt-mens-trousers_173815-46040.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 30,
    description: "A durable leather belt with a modern buckle.",
    reviews: 4.5,
    stock: 50,
    likes: 85,
    comments: 10,
    category: "Accessories",
    quantity: 12,
    sizes: ["LG", "MD", "SM"],
    colors: ["Black", "Brown", "SteelBlue"],
    gender: "Men",
  },
  {
    id: "16",
    title: "Women's Leather Boots",
    status: "Regular",
    season: "Winter",
    images: [
      "https://img.freepik.com/free-photo/confident-young-lady-sitting-swing-chair-colorful-background-high-quality-photo_144627-74080.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/premium-photo/woman-near-tree-logs-fashion-posing_133748-22225.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/woman-shoes-close-up_1303-12939.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 200,
    description: "Elegant leather boots perfect for winter outings.",
    reviews: 4.6,
    stock: 15,
    likes: 120,
    comments: 15,
    category: "Footwear",
    quantity: 11,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "Brown", "CadetBlue"],
    gender: "Women",
  },
  {
    id: "17",
    title: "Kids Raincoat",
    status: "Regular",
    season: "Winter",
    images: [
      "https://img.freepik.com/free-photo/portrait-smiling-young-girl_1328-4050.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/medium-shot-young-woman-looking-up_23-2148610341.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/little-boy-wearing-rain-coat_23-2148619388.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
      "https://img.freepik.com/free-photo/boy-holding-closed-umbrella_23-2148619345.jpg?ga=GA1.1.1093837504.1727806851&semt=ais_hybrid",
    ],
    price: 45,
    description: "Waterproof raincoat to keep your kids dry and comfy.",
    reviews: 4.4,
    stock: 30,
    likes: 65,
    comments: 10,
    category: "Outerwear",
    quantity: 13,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Brown", "Red", "Blue", "Yellow"],
    gender: "Kid",
  },
  {
    id: "18",
    title: "Men's Slim Fit Jeans",
    status: "New Arrival",
    season: "Winter",
    images: ["jeans1.jpg", "jeans2.jpg"],
    price: 70,
    description: "Trendy slim-fit jeans for a modern look.",
    reviews: 4.7,
    stock: 25,
    likes: 95,
    comments: 12,
    category: "Pants",
    quantity: 31,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Black"],
    gender: "Men",
  },
  {
    id: "19",
    title: "Women's Cotton Cardigan",
    status: "New Arrival",
    season: "Winter",
    images: ["cardigan1.jpg", "cardigan2.jpg"],
    price: 90,
    description: "A soft cotton cardigan to keep you warm.",
    reviews: 4.6,
    stock: 12,
    likes: 110,
    comments: 8,
    category: "Outerwear",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Black", "Green"],
    gender: "Women",
  },
  {
    id: "20",
    title: "Kids Summer Shorts",
    status: "Regular",
    season: "Summer",
    images: ["shorts1.jpg", "shorts2.jpg"],
    price: 25,
    description: "Light and airy shorts for active kids.",
    reviews: 4.2,
    stock: 40,
    likes: 50,
    comments: 5,
    category: "Pants",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Red", "Blue", "Yellow"],
    gender: "Kid",
  },

  {
    id: "21",
    title: "Classic Men's Leather Jacket",
    status: "Top Sell",
    season: "Winter",
    images: ["leather_jacket1.jpg", "leather_jacket2.jpg"],
    price: 250,
    description: "A timeless leather jacket for a bold and stylish look.",
    reviews: 4.9,
    stock: 10,
    likes: 180,
    comments: 25,
    category: "Outerwear",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "Brown"],
    gender: "Men",
  },
  {
    id: "22",
    title: "Women's Floral Summer Dress",
    status: "New Arrival",
    season: "Summer",
    images: ["summer_dress1.jpg", "summer_dress2.jpg"],
    price: 120,
    description: "A light and breezy floral dress for summer outings.",
    reviews: 4.7,
    stock: 15,
    likes: 150,
    comments: 20,
    category: "Dresses",
    quantity: 1,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Blue", "Green"],
    gender: "Women",
  },
  {
    id: "23",
    title: "Kids Denim Jacket",
    status: "Upcoming",
    season: "Winter",
    images: ["denim_jacket1.jpg", "denim_jacket2.jpg"],
    price: 80,
    description: "Stylish denim jacket for kids to rock a cool look.",
    reviews: 4.5,
    stock: 20,
    likes: 45,
    comments: 80,
    category: "Outerwear",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Black"],
    gender: "Kid",
  },
  {
    id: "24",
    title: "Men's Athletic Sneakers",
    status: "Regular",
    season: "Summer",
    images: ["sneakers1.jpg", "sneakers2.jpg"],
    price: 100,
    description: "Comfortable and durable sneakers for active lifestyles.",
    reviews: 4.5,
    stock: 25,
    likes: 90,
    comments: 12,
    category: "Footwear",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Black", "Red"],
    gender: "Men",
  },
  {
    id: "25",
    title: "Women's High Heels",
    status: "Top Sell",
    season: "Summer",
    images: ["high_heels1.jpg", "high_heels2.jpg"],
    price: 180,
    description: "Elegant high heels for formal occasions and parties.",
    reviews: 4.8,
    stock: 12,
    likes: 140,
    comments: 18,
    category: "Footwear",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Red", "Black", "White"],
    gender: "Women",
  },
  {
    id: "26",
    title: "Kids Graphic T-Shirt",
    status: "New Arrival",
    season: "Summer",
    images: ["graphic_tshirt1.jpg", "graphic_tshirt2.jpg"],
    price: 35,
    description: "Fun and colorful T-shirts with playful graphics for kids.",
    reviews: 4.6,
    stock: 30,
    likes: 80,
    comments: 10,
    category: "Shirts",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Red", "Yellow"],
    gender: "Kid",
  },

  {
    id: "27",
    title: "Men's Cotton Polo Shirt",
    status: "New Arrival",
    season: "Summer",
    images: ["polo_shirt1.jpg", "polo_shirt2.jpg"],
    price: 50,
    description: "A lightweight and breathable polo shirt for casual wear.",
    reviews: 4.5,
    stock: 40,
    likes: 120,
    comments: 14,
    category: "Shirts",
    quantity: 15,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Blue", "Black"],
    gender: "Men",
  },
  {
    id: "28",
    title: "Women's Casual Blazer",
    status: "Top Sell",
    season: "Winter",
    images: ["casual_blazer1.jpg", "casual_blazer2.jpg"],
    price: 140,
    description: "A stylish blazer that combines comfort and elegance.",
    reviews: 4.7,
    stock: 15,
    likes: 180,
    comments: 20,
    category: "Outerwear",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "Beige", "Gray"],
    gender: "Women",
  },
  {
    id: "29",
    title: "Kids Waterproof Winter Boots",
    status: "Upcoming",
    season: "Winter",
    images: ["winter_boots1.jpg", "winter_boots2.jpg"],
    price: 70,
    description:
      "Durable and waterproof boots to keep kids' feet warm and dry.",
    reviews: null,
    stock: 25,
    likes: 20,
    comments: 10,
    category: "Footwear",
    quantity: 1,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "Brown", "Gray"],
    gender: "Kid",
  },
  {
    id: "30",
    title: "Men's Slim-Fit Jeans",
    status: "Regular",
    season: "All Season",
    images: ["slim_fit_jeans1.jpg", "slim_fit_jeans2.jpg"],
    price: 80,
    description: "Comfortable slim-fit jeans for everyday wear.",
    reviews: 4.6,
    stock: 30,
    likes: 110,
    comments: 15,
    category: "Pants",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Black"],
    gender: "Men",
  },
  {
    id: "31",
    title: "Women's Wool Scarf",
    status: "New Arrival",
    season: "Winter",
    images: ["wool_scarf1.jpg", "wool_scarf2.jpg"],
    price: 45,
    description: "A warm and cozy wool scarf for chilly days.",
    reviews: 4.8,
    stock: 50,
    likes: 200,
    comments: 22,
    category: "Accessories",
    quantity: 12,
    sizes: ["One Size"],
    colors: ["Red", "Gray", "White"],
    gender: "Women",
  },
  {
    id: "32",
    title: "Kids Cartoon Hoodie",
    status: "Top Sell",
    season: "Winter",
    images: ["cartoon_hoodie1.jpg", "cartoon_hoodie2.jpg"],
    price: 60,
    description: "A cute and cozy hoodie with fun cartoon designs.",
    reviews: 4.9,
    stock: 20,
    likes: 150,
    comments: 18,
    category: "Hoodies",
    quantity: 14,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Yellow", "Pink"],
    gender: "Kid",
  },
  {
    id: "33",
    title: "Men's Woolen Sweater",
    status: "Upcoming",
    season: "Winter",
    images: ["woolen_sweater1.jpg", "woolen_sweater2.jpg"],
    price: 100,
    description: "A premium woolen sweater for warmth and style.",
    reviews: null,
    stock: 18,
    likes: 20,
    comments: 10,
    category: "Sweaters",
    quantity: 11,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Gray", "Black", "Navy"],
    gender: "Men",
  },
  {
    id: "34",
    title: "Women's Elegant Evening Gown",
    status: "Regular",
    season: "All Season",
    images: ["evening_gown1.jpg", "evening_gown2.jpg"],
    price: 250,
    description: "An exquisite evening gown for formal occasions.",
    reviews: 4.9,
    stock: 10,
    likes: 220,
    comments: 30,
    category: "Dresses",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Red", "Black", "Gold"],
    gender: "Women",
  },
];

export interface Product {
  id: string;
  title: string;
  status: string;
  season: string;
  images?: string[];
  price: number;
  description: string;
  reviews: number;
  stock: number;
  likes: number;
  comments: string;
  category: string;
  quantity: number;
  sizes: string[];
  colors: string[];
  gender: string;
}
export type Products = {
  id: string;
  title: string;
  price: number;
  images: string[];
  colors?: string[];
  status: string;
};
