export const productDatas = [
  {
    id: "1",
    title: "Classic Winter Jacket",
    status: "New Arrival",
    season: "Winter",
    images: ["winter_jacket1.jpg", "winter_jacket2.jpg"],
    price: 120,
    description: "A warm and stylish jacket perfect for winter outings.",
    reviews: 4.5,
    stock: 15,
    likes: 120,
    comments: 25,
    category: "Outerwear",
    quantity: 31,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Red", "Black", "Blue"],
    gender: "Men",
  },
  {
    id: "2",
    title: "Elegant Evening Gown",
    status: "New Arrival",
    season: "Winter",
    images: ["evening_gown1.jpg", "evening_gown2.jpg"],
    price: 220,
    description: "A stunning evening gown designed to make you shine.",
    reviews: 4.8,
    stock: 10,
    likes: 140,
    comments: 30,
    category: "Dresses",
    quantity: 11,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Black", "Green"],
    gender: "Women",
  },
  {
    id: "3",
    title: "Stylish Kids Winter Coat",
    status: "New Arrival",
    season: "Winter",
    images: ["kids_coat1.jpg", "kids_coat2.jpg"],
    price: 80,
    description: "Keep your kids warm and stylish this winter.",
    reviews: 4.6,
    stock: 20,
    likes: 95,
    comments: 15,
    category: "Outerwear",
    quantity: 91,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Red", "Black"],
    gender: "Kid",
  },
  {
    id: "4",
    title: "Summer Linen Shirt",
    status: "New Arrival",
    season: "Summer",
    images: ["linen_shirt1.jpg", "linen_shirt2.jpg"],
    price: 55,
    description: "Lightweight and breathable linen shirt for hot summer days.",
    reviews: 4.3,
    stock: 25,
    likes: 80,
    comments: 10,
    category: "Shirts",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Green"],
    gender: "Men",
  },
  {
    id: "5",
    title: "Chic Summer Dress",
    status: "New Arrival",
    season: "Summer",
    images: ["summer_dress1.jpg", "summer_dress2.jpg"],
    price: 100,
    description: "A chic dress perfect for sunny summer days.",
    reviews: 4.7,
    stock: 12,
    likes: 110,
    comments: 20,
    category: "Dresses",
    quantity: 41,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "White", "Red"],
    gender: "Women",
  },
  {
    id: "6",
    title: "Kids Summer T-Shirt",
    status: "New Arrival",
    season: "Summer",
    images: ["kids_tshirt1.jpg", "kids_tshirt2.jpg"],
    price: 30,
    description: "Soft and colorful t-shirt for kids to enjoy summer fun.",
    reviews: 4.9,
    stock: 30,
    likes: 70,
    comments: 5,
    category: "T-Shirts",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Green", "Blue", "White"],
    gender: "Kid",
  },
  {
    id: "7",
    title: "Formal Men’s Suit",
    status: "Top Sell",
    season: "Winter",
    images: ["formal_suit1.jpg", "formal_suit2.jpg"],
    price: 300,
    description: "A premium suit for business and formal occasions.",
    reviews: 4.9,
    stock: 5,
    likes: 200,
    comments: 45,
    category: "Suits",
    quantity: 31,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "Blue"],
    gender: "Men",
  },
  {
    id: "8",
    title: "Women's Office Blazer",
    status: "Top Sell",
    season: "Winter",
    images: ["office_blazer1.jpg", "office_blazer2.jpg"],
    price: 180,
    description: "A classic blazer for professional settings.",
    reviews: 4.6,
    stock: 8,
    likes: 170,
    comments: 35,
    category: "Outerwear",
    quantity: 31,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "White"],
    gender: "Women",
  },
  {
    id: "9",
    title: "Casual Sneakers",
    status: "Upcoming",
    season: "Summer",
    images: ["sneakers1.jpg", "sneakers2.jpg"],
    price: 75,
    description: "Comfortable and stylish sneakers for everyday wear.",
    reviews: 4.5,
    stock: 50,
    likes: 55,
    comments: 6,
    category: "Footwear",
    quantity: 41,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Black", "Blue"],
    gender: "Men",
  },
  {
    id: "10",
    title: "Stylish Kid’s Backpack",
    status: "Upcoming",
    season: "Summer",
    images: ["kids_backpack1.jpg", "kids_backpack2.jpg"],
    price: 50,
    description: "Perfect for school or travel, designed for kids.",
    reviews: 4.9,
    stock: 20,
    likes: 44,
    comments: 8,
    category: "Accessories",
    quantity: 11,
    sizes: [],
    colors: ["Blue", "Green", "Red"],
    gender: "Kid",
  },

  {
    id: "11",
    title: "Trendy Men’s Polo Shirt",
    status: "Upcoming",
    season: "Summer",
    images: ["polo_shirt1.jpg", "polo_shirt2.jpg"],
    price: 40,
    description: "A classic polo shirt for casual outings.",
    reviews: 4.5,
    stock: 35,
    likes: 7,
    comments: 33,
    category: "Shirts",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Black", "Green"],
    gender: "Men",
  },
  {
    id: "12",
    title: "Elegant Women's Handbag",
    status: "Upcoming",
    season: "Summer",
    images: ["handbag1.jpg", "handbag2.jpg"],
    price: 150,
    description: "A stylish handbag to complement your outfit.",
    reviews: 4.7,
    stock: 18,
    likes: 6,
    comments: 33,
    category: "Accessories",
    quantity: 13,
    sizes: [],
    colors: ["Black", "White", "Red"],
    gender: "Women",
  },
  {
    id: "13",
    title: "Warm Knitted Scarf",
    status: "Top Sell",
    season: "Winter",
    images: ["scarf1.jpg", "scarf2.jpg"],
    price: 25,
    description: "A cozy scarf to keep you warm and stylish.",
    reviews: 4.7,
    stock: 40,
    likes: 110,
    comments: 20,
    category: "Accessories",
    quantity: 1,
    sizes: [],
    colors: ["Red", "Black", "White"],
    gender: "Men",
  },
  {
    id: "14",
    title: "Kids Winter Boots",
    status: "Top Sell",
    season: "Winter",
    images: ["winter_boots1.jpg", "winter_boots2.jpg"],
    price: 60,
    description: "Durable boots for kids to enjoy snowy adventures.",
    reviews: 4.8,
    stock: 20,
    likes: 140,
    comments: 18,
    category: "Footwear",
    quantity: 16,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Black", "White"],
    gender: "Kid",
  },
  {
    id: "15",
    title: "Leather Men's Belt",
    status: "Regular",
    season: "Winter",
    images: ["belt1.jpg", "belt2.jpg"],
    price: 30,
    description: "A durable leather belt with a modern buckle.",
    reviews: 4.5,
    stock: 50,
    likes: 85,
    comments: 10,
    category: "Accessories",
    quantity: 12,
    sizes: [],
    colors: ["Black", "Brown"],
    gender: "Men",
  },
  {
    id: "16",
    title: "Women's Leather Boots",
    status: "Regular",
    season: "Winter",
    images: ["leather_boots1.jpg", "leather_boots2.jpg"],
    price: 200,
    description: "Elegant leather boots perfect for winter outings.",
    reviews: 4.6,
    stock: 15,
    likes: 120,
    comments: 15,
    category: "Footwear",
    quantity: 11,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "Brown"],
    gender: "Women",
  },
  {
    id: "17",
    title: "Kids Raincoat",
    status: "Regular",
    season: "Winter",
    images: ["raincoat1.jpg", "raincoat2.jpg"],
    price: 45,
    description: "Waterproof raincoat to keep your kids dry and comfy.",
    reviews: 4.4,
    stock: 30,
    likes: 65,
    comments: 10,
    category: "Outerwear",
    quantity: 13,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Red", "Blue", "Yellow"],
    gender: "Kid",
  },
  {
    id: "18",
    title: "Men's Slim Fit Jeans",
    status: "New Arrival",
    season: "Winter",
    images: ["jeans1.jpg", "jeans2.jpg"],
    price: 70,
    description: "Trendy slim-fit jeans for a modern look.",
    reviews: 4.7,
    stock: 25,
    likes: 95,
    comments: 12,
    category: "Pants",
    quantity: 31,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Black"],
    gender: "Men",
  },
  {
    id: "19",
    title: "Women's Cotton Cardigan",
    status: "New Arrival",
    season: "Winter",
    images: ["cardigan1.jpg", "cardigan2.jpg"],
    price: 90,
    description: "A soft cotton cardigan to keep you warm.",
    reviews: 4.6,
    stock: 12,
    likes: 110,
    comments: 8,
    category: "Outerwear",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Black", "Green"],
    gender: "Women",
  },
  {
    id: "20",
    title: "Kids Summer Shorts",
    status: "Regular",
    season: "Summer",
    images: ["shorts1.jpg", "shorts2.jpg"],
    price: 25,
    description: "Light and airy shorts for active kids.",
    reviews: 4.2,
    stock: 40,
    likes: 50,
    comments: 5,
    category: "Pants",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Red", "Blue", "Yellow"],
    gender: "Kid",
  },

  {
    id: "21",
    title: "Classic Men's Leather Jacket",
    status: "Top Sell",
    season: "Winter",
    images: ["leather_jacket1.jpg", "leather_jacket2.jpg"],
    price: 250,
    description: "A timeless leather jacket for a bold and stylish look.",
    reviews: 4.9,
    stock: 10,
    likes: 180,
    comments: 25,
    category: "Outerwear",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "Brown"],
    gender: "Men",
  },
  {
    id: "22",
    title: "Women's Floral Summer Dress",
    status: "New Arrival",
    season: "Summer",
    images: ["summer_dress1.jpg", "summer_dress2.jpg"],
    price: 120,
    description: "A light and breezy floral dress for summer outings.",
    reviews: 4.7,
    stock: 15,
    likes: 150,
    comments: 20,
    category: "Dresses",
    quantity: 1,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Blue", "Green"],
    gender: "Women",
  },
  {
    id: "23",
    title: "Kids Denim Jacket",
    status: "Upcoming",
    season: "Winter",
    images: ["denim_jacket1.jpg", "denim_jacket2.jpg"],
    price: 80,
    description: "Stylish denim jacket for kids to rock a cool look.",
    reviews: 4.5,
    stock: 20,
    likes: 45,
    comments: 80,
    category: "Outerwear",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Black"],
    gender: "Kid",
  },
  {
    id: "24",
    title: "Men's Athletic Sneakers",
    status: "Regular",
    season: "Summer",
    images: ["sneakers1.jpg", "sneakers2.jpg"],
    price: 100,
    description: "Comfortable and durable sneakers for active lifestyles.",
    reviews: 4.5,
    stock: 25,
    likes: 90,
    comments: 12,
    category: "Footwear",
    quantity: 21,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Black", "Red"],
    gender: "Men",
  },
  {
    id: "25",
    title: "Women's High Heels",
    status: "Top Sell",
    season: "Summer",
    images: ["high_heels1.jpg", "high_heels2.jpg"],
    price: 180,
    description: "Elegant high heels for formal occasions and parties.",
    reviews: 4.8,
    stock: 12,
    likes: 140,
    comments: 18,
    category: "Footwear",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Red", "Black", "White"],
    gender: "Women",
  },
  {
    id: "26",
    title: "Kids Graphic T-Shirt",
    status: "New Arrival",
    season: "Summer",
    images: ["graphic_tshirt1.jpg", "graphic_tshirt2.jpg"],
    price: 35,
    description: "Fun and colorful T-shirts with playful graphics for kids.",
    reviews: 4.6,
    stock: 30,
    likes: 80,
    comments: 10,
    category: "Shirts",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Red", "Yellow"],
    gender: "Kid",
  },

  {
    id: "27",
    title: "Men's Cotton Polo Shirt",
    status: "New Arrival",
    season: "Summer",
    images: ["polo_shirt1.jpg", "polo_shirt2.jpg"],
    price: 50,
    description: "A lightweight and breathable polo shirt for casual wear.",
    reviews: 4.5,
    stock: 40,
    likes: 120,
    comments: 14,
    category: "Shirts",
    quantity: 15,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["White", "Blue", "Black"],
    gender: "Men",
  },
  {
    id: "28",
    title: "Women's Casual Blazer",
    status: "Top Sell",
    season: "Winter",
    images: ["casual_blazer1.jpg", "casual_blazer2.jpg"],
    price: 140,
    description: "A stylish blazer that combines comfort and elegance.",
    reviews: 4.7,
    stock: 15,
    likes: 180,
    comments: 20,
    category: "Outerwear",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "Beige", "Gray"],
    gender: "Women",
  },
  {
    id: "29",
    title: "Kids Waterproof Winter Boots",
    status: "Upcoming",
    season: "Winter",
    images: ["winter_boots1.jpg", "winter_boots2.jpg"],
    price: 70,
    description:
      "Durable and waterproof boots to keep kids' feet warm and dry.",
    reviews: null,
    stock: 25,
    likes: 20,
    comments: 10,
    category: "Footwear",
    quantity: 1,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Black", "Brown", "Gray"],
    gender: "Kid",
  },
  {
    id: "30",
    title: "Men's Slim-Fit Jeans",
    status: "Regular",
    season: "All Season",
    images: ["slim_fit_jeans1.jpg", "slim_fit_jeans2.jpg"],
    price: 80,
    description: "Comfortable slim-fit jeans for everyday wear.",
    reviews: 4.6,
    stock: 30,
    likes: 110,
    comments: 15,
    category: "Pants",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Black"],
    gender: "Men",
  },
  {
    id: "31",
    title: "Women's Wool Scarf",
    status: "New Arrival",
    season: "Winter",
    images: ["wool_scarf1.jpg", "wool_scarf2.jpg"],
    price: 45,
    description: "A warm and cozy wool scarf for chilly days.",
    reviews: 4.8,
    stock: 50,
    likes: 200,
    comments: 22,
    category: "Accessories",
    quantity: 12,
    sizes: ["One Size"],
    colors: ["Red", "Gray", "White"],
    gender: "Women",
  },
  {
    id: "32",
    title: "Kids Cartoon Hoodie",
    status: "Top Sell",
    season: "Winter",
    images: ["cartoon_hoodie1.jpg", "cartoon_hoodie2.jpg"],
    price: 60,
    description: "A cute and cozy hoodie with fun cartoon designs.",
    reviews: 4.9,
    stock: 20,
    likes: 150,
    comments: 18,
    category: "Hoodies",
    quantity: 14,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Blue", "Yellow", "Pink"],
    gender: "Kid",
  },
  {
    id: "33",
    title: "Men's Woolen Sweater",
    status: "Upcoming",
    season: "Winter",
    images: ["woolen_sweater1.jpg", "woolen_sweater2.jpg"],
    price: 100,
    description: "A premium woolen sweater for warmth and style.",
    reviews: null,
    stock: 18,
    likes: 20,
    comments: 10,
    category: "Sweaters",
    quantity: 11,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Gray", "Black", "Navy"],
    gender: "Men",
  },
  {
    id: "34",
    title: "Women's Elegant Evening Gown",
    status: "Regular",
    season: "All Season",
    images: ["evening_gown1.jpg", "evening_gown2.jpg"],
    price: 250,
    description: "An exquisite evening gown for formal occasions.",
    reviews: 4.9,
    stock: 10,
    likes: 220,
    comments: 30,
    category: "Dresses",
    quantity: 12,
    sizes: ["XXL", "XL", "LG", "MD", "SM"],
    colors: ["Red", "Black", "Gold"],
    gender: "Women",
  },
];

export interface Product {
  id: string | null | undefined;
  title: string | null | undefined;
  status: string | null | undefined;
  season: string | null | undefined;
  images: string[] | null | undefined;
  price: number | null | undefined;
  description: string | null | undefined;
  reviews: number | null | undefined;
  stock: number | null;
  likes: number | null;
  comments: number | null;
  category: string | null | undefined;
  quantity: number | null | undefined;
  sizes: string[] | null | undefined;
  colors: string[] | null | undefined;
  gender: string | null | undefined;
}
